# Generated by Django 4.0.3 on 2022-04-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_arquivo_final_alter_jobs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='preco',
        ),
        migrations.AddField(
            model_name='jobs',
            name='solicitante',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='categoria',
            field=models.CharField(choices=[('M', 'Mofificação'), ('ND', 'Nova Demanda')], default='M', max_length=2),
        ),
    ]
