# Generated by Django 4.0.3 on 2022-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobs_preco_jobs_solicitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='arquivo_final',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
